### ISSUE TITLE
麻烦问一下， 在platformio中， 环境应该选择哪个？

### ISSUE THREAD

**Issue by adsian** [track-tech/-ESP32C3_LCD_Screen_button_Demo#1]
#include <Adafruit_GFX.h>    //核心图形库
#include <Adafruit_ST7735.h> //为ST7735硬件专用库
#include "Adafruit_ST77xx.h" //提供屏幕旋转功能

在
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
环境下， 这些头文件是找不到了，麻烦楼主指导一下

**Comment by track-tech** [comment]
我使用的是Arduino+VScode开发的，platformio下的环境配置不太熟悉，抱歉没能帮到你

**Comment by adsian** [comment]
我是根据这篇文章配置的 https://blog.51cto.com/u_15259603/2878904 ， clion 也支持platformio了，比vscode体验更好一些

在platform.ini中加入库依赖配置

lib_deps =
    Arduino Library
    Adafruit ST7735 and ST7789 Library
    Adafruit GFX Library


pio run 会把这些毛添加到lib里

如果出现头文件#inculde <xxxx.h>无法连接的的情况

在CMakeLists.txt中添加library

include_directories("./.pio/libdeps/esp32-c3-devkitm-1/Adafruit BusIO")
include_directories("./.pio/libdeps/esp32-c3-devkitm-1/Adafruit GFX Library")
include_directories("./.pio/libdeps/esp32-c3-devkitm-1/Adafruit seesaw Library")
include_directories("./.pio/libdeps/esp32-c3-devkitm-1/Adafruit ST7735 and ST7789 Library")


然后右键reload就可以

**Comment by track-tech** [comment]
学到了，感谢 :P
